### ISSUE TITLE
installation du bot

### ISSUE THREAD

**Issue by Nathan210032** [Redemption007/V2Engine#1]
salut pourrais tu me dire comment on installe le bot stp

**Comment by Redemption007** [comment]
Bonjour,
Tu copies/colle le code source et tu suis les instructions dans le README.md
Mais même si ce projet est en open source, il n'est pas encore tout à fait stable. N'étant pas développeur de métier, je n'ai pas le temps de faire des updates régulièrement, ainsi le code peut contenir des erreurs inconvenantes.
Bonne journée à toi
